using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rebuild.Analyzers
{
    /// <summary>
    /// Compiles data/buildings.json (passed as AdditionalFiles) into C# tables (docs/06-economy.md §1), so the
    /// simulation never parses JSON at runtime. Building order in the file is the type index used by commands.
    /// Also emits <c>BuildingIds</c> constants, so code that needs a specific building fails to build without it.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class BuildingDataGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor BadData = new DiagnosticDescriptor(
            "RB0101", "Invalid building data", "{0}: {1}", "Data", DiagnosticSeverity.Error, isEnabledByDefault: true);

        /// <summary>Upper bound of radius and cost values (they are serialized as one byte).</summary>
        private const long MaxSmallValue = 255;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var files = context.AdditionalTextsProvider
                .Where(f => Path.GetFileName(f.Path) == "buildings.json")
                .Select((f, ct) => new FileData(f.Path, f.GetText(ct)?.ToString() ?? ""))
                .Collect();
            context.RegisterSourceOutput(files, Emit);
        }

        private sealed class FileData
        {
            public FileData(string path, string text) { Path = path; Text = text.Replace("\r", ""); }
            public string Path { get; }
            public string Text { get; }
        }

        private sealed class Building
        {
            public string Id = "";
            public string Name = "";
            public string Size = "";
            public string Placement = "";
            public long Territory;
            public long Planks;
            public long Stone;
            public bool PlayerPlaceable = true;
        }

        private static void Emit(SourceProductionContext ctx, ImmutableArray<FileData> files)
        {
            if (files.Length == 0) return; // projects without building data (tools, tests)
            if (files.Length != 1)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(BadData, Location.None, "buildings.json",
                    "expected exactly one buildings.json, found " + files.Length.ToString(CultureInfo.InvariantCulture)));
                return;
            }
            var file = files[0];
            List<Building> buildings;
            try { buildings = ReadBuildings(file.Text); }
            catch (Exception e) when (CultureDataGenerator.IsDataError(e))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(BadData, Location.None, file.Path, e.Message));
                return;
            }

            // FNV-1a 64 over the LF-normalized file, so all OS agree (same scheme as the culture data hash).
            ulong hash = 14695981039346656037UL;
            foreach (byte b in Encoding.UTF8.GetBytes(file.Text))
            {
                hash ^= b;
                hash *= 1099511628211UL;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> by Rebuild.Analyzers.BuildingDataGenerator from data/buildings.json </auto-generated>");
            sb.AppendLine("namespace Rebuild.Sim.Buildings;");
            sb.AppendLine();
            sb.AppendLine("public static partial class BuildingCatalog");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Hash of data/buildings.json; part of GameVersion.</summary>");
            sb.AppendLine("    public const ulong DataHash = 0x" + hash.ToString("X16", CultureInfo.InvariantCulture) + "UL;");
            sb.AppendLine();
            sb.AppendLine("    private static BuildingDefinition[] CreateAll() => new BuildingDefinition[]");
            sb.AppendLine("    {");
            for (int i = 0; i < buildings.Count; i++)
            {
                var b = buildings[i];
                sb.Append("        new BuildingDefinition(").Append(i).Append(", ")
                  .Append(Literal(b.Id)).Append(", ").Append(Literal(b.Name)).Append(", ")
                  .Append("BuildingSize.").Append(b.Size).Append(", ")
                  .Append("BuildingTerrain.").Append(b.Placement).Append(", ")
                  .Append(b.Territory.ToString(CultureInfo.InvariantCulture)).Append(", ")
                  .Append(b.Planks.ToString(CultureInfo.InvariantCulture)).Append(", ")
                  .Append(b.Stone.ToString(CultureInfo.InvariantCulture)).Append(", ")
                  .Append(b.PlayerPlaceable ? "true" : "false").AppendLine("),");
            }
            sb.AppendLine("    };");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Type index of every building in data/buildings.json.</summary>");
            sb.AppendLine("public static class BuildingIds");
            sb.AppendLine("{");
            for (int i = 0; i < buildings.Count; i++)
                sb.Append("    public const ushort ").Append(CultureDataGenerator.PascalCase(buildings[i].Id))
                  .Append(" = ").Append(i).AppendLine(";");
            sb.AppendLine("}");
            ctx.AddSource("BuildingCatalog.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static List<Building> ReadBuildings(string text)
        {
            var root = (List<KeyValuePair<string, object?>>)MiniJson.Parse(text)!;
            var list = new List<Building>();
            foreach (var kv in root)
            {
                switch (kv.Key)
                {
                    case "buildings":
                        foreach (var item in (List<object?>)kv.Value!)
                            list.Add(ReadBuilding((List<KeyValuePair<string, object?>>)item!));
                        break;
                    case "$comment": break;
                    default: throw new FormatException("unknown field '" + kv.Key + "'");
                }
            }
            if (list.Count == 0) throw new FormatException("no buildings");
            if (list.Count > ushort.MaxValue) throw new FormatException("too many buildings");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var b in list)
                if (!seen.Add(CultureDataGenerator.PascalCase(b.Id))) throw new FormatException("duplicate id '" + b.Id + "'");
            return list;
        }

        private static Building ReadBuilding(List<KeyValuePair<string, object?>> obj)
        {
            var b = new Building();
            foreach (var kv in obj)
            {
                switch (kv.Key)
                {
                    case "id": b.Id = (string)kv.Value!; break;
                    case "name": b.Name = (string)kv.Value!; break;
                    case "size":
                        switch ((string)kv.Value!)
                        {
                            case "S": b.Size = "Small"; break;
                            case "M": b.Size = "Medium"; break;
                            case "L": b.Size = "Large"; break;
                            default: throw new FormatException("size must be S, M or L");
                        }
                        break;
                    case "placement":
                        switch ((string)kv.Value!)
                        {
                            case "land": b.Placement = "Land"; break;
                            case "mountain": b.Placement = "Mountain"; break;
                            default: throw new FormatException("placement must be land or mountain");
                        }
                        break;
                    case "territory": b.Territory = Small(kv); break;
                    case "cost":
                        foreach (var c in (List<KeyValuePair<string, object?>>)kv.Value!)
                        {
                            switch (c.Key)
                            {
                                case "plank": b.Planks = Small(c); break;
                                case "stone": b.Stone = Small(c); break;
                                default: throw new FormatException("unknown cost good '" + c.Key + "'");
                            }
                        }
                        break;
                    case "player_placeable": b.PlayerPlaceable = (bool)kv.Value!; break;
                    default: throw new FormatException("unknown field '" + kv.Key + "'");
                }
            }
            if (b.Id.Length == 0) throw new FormatException("building without 'id'");
            foreach (char ch in b.Id)
                if (!(ch >= 'a' && ch <= 'z') && !(ch >= '0' && ch <= '9') && ch != '_')
                    throw new FormatException("id '" + b.Id + "' must be lower snake case");
            if (b.Size.Length == 0) throw new FormatException("'" + b.Id + "' has no size");
            if (b.Placement.Length == 0) throw new FormatException("'" + b.Id + "' has no placement");
            if (b.Name.Length == 0) b.Name = b.Id;
            return b;
        }

        private static long Small(KeyValuePair<string, object?> kv)
        {
            long v = (long)kv.Value!;
            if (v < 0 || v > MaxSmallValue) throw new FormatException("'" + kv.Key + "' must be 0..255");
            return v;
        }

        private static string Literal(string s) =>
            "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
