using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rebuild.Analyzers
{
    /// <summary>
    /// Compiles data/cultures/&lt;id&gt;/culture.json (passed as AdditionalFiles) into C# tables, so the
    /// simulation never parses JSON at runtime and definition order is fixed (ADR 0007).
    /// Unknown modifier keys or hooks fail the build because the generated code references enum members.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class CultureDataGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor BadData = new DiagnosticDescriptor(
            "RB0100", "Invalid culture data", "{0}: {1}", "Data", DiagnosticSeverity.Error, isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var files = context.AdditionalTextsProvider
                .Where(f => Path.GetFileName(f.Path) == "culture.json")
                .Select((f, ct) => new FileData(f.Path, f.GetText(ct)?.ToString() ?? ""))
                .Collect();
            context.RegisterSourceOutput(files, Emit);
        }

        private sealed class FileData
        {
            public FileData(string path, string text) { Path = path; Text = text.Replace("\r", ""); }
            public string Path { get; }
            public string Text { get; }
        }

        private sealed class Culture
        {
            public string Id = "";
            public string Name = "";
            public string Text = "";
            public List<KeyValuePair<string, long>> Modifiers = new List<KeyValuePair<string, long>>();
            public List<string> Hooks = new List<string>();
        }

        private static void Emit(SourceProductionContext ctx, ImmutableArray<FileData> files)
        {
            var cultures = new List<Culture>();
            foreach (var f in files)
            {
                try { cultures.Add(ReadCulture(f)); }
                catch (Exception e) when (e is FormatException || e is InvalidCastException || e is KeyNotFoundException)
                {
                    ctx.ReportDiagnostic(Diagnostic.Create(BadData, Location.None, f.Path, e.Message));
                    return;
                }
            }
            cultures.Sort((a, b) => string.CompareOrdinal(a.Id, b.Id));

            // FNV-1a 64 over "id\ncontent\n" in id order; LF-normalized so all OS agree.
            ulong hash = 14695981039346656037UL;
            foreach (var c in cultures)
                foreach (byte b in Encoding.UTF8.GetBytes(c.Id + "\n" + c.Text + "\n"))
                {
                    hash ^= b;
                    hash *= 1099511628211UL;
                }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> by Rebuild.Analyzers.CultureDataGenerator from data/cultures/*/culture.json </auto-generated>");
            sb.AppendLine("namespace Rebuild.Sim.Cultures;");
            sb.AppendLine();
            sb.AppendLine("public static partial class CultureCatalog");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Hash of all culture data files; part of GameVersion.</summary>");
            sb.AppendLine("    public const ulong DataHash = 0x" + hash.ToString("X16", CultureInfo.InvariantCulture) + "UL;");
            sb.AppendLine();
            sb.AppendLine("    private static CultureDefinition[] CreateAll() => new CultureDefinition[]");
            sb.AppendLine("    {");
            for (int i = 0; i < cultures.Count; i++)
            {
                var c = cultures[i];
                sb.Append("        new CultureDefinition(").Append(i).Append(", ")
                  .Append(Literal(c.Id)).Append(", ").Append(Literal(c.Name)).AppendLine(",");
                sb.Append("            new ModifierEntry[] { ");
                foreach (var m in c.Modifiers)
                    sb.Append("new ModifierEntry(ModifierKey.").Append(PascalCase(m.Key)).Append(", ")
                      .Append(m.Value.ToString(CultureInfo.InvariantCulture)).Append("), ");
                sb.AppendLine("},");
                sb.Append("            new CultureHook[] { ");
                foreach (var h in c.Hooks)
                    sb.Append("CultureHook.").Append(PascalCase(h)).Append(", ");
                sb.AppendLine("}),");
            }
            sb.AppendLine("    };");
            sb.AppendLine("}");
            ctx.AddSource("CultureCatalog.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static Culture ReadCulture(FileData f)
        {
            var root = (List<KeyValuePair<string, object?>>)MiniJson.Parse(f.Text)!;
            var c = new Culture { Text = f.Text };
            foreach (var kv in root)
            {
                switch (kv.Key)
                {
                    case "id": c.Id = (string)kv.Value!; break;
                    case "name": c.Name = (string)kv.Value!; break;
                    case "modifiers":
                        foreach (var m in (List<KeyValuePair<string, object?>>)kv.Value!)
                            c.Modifiers.Add(new KeyValuePair<string, long>(m.Key, (long)m.Value!));
                        break;
                    case "hooks":
                        foreach (var h in (List<object?>)kv.Value!) c.Hooks.Add((string)h!);
                        break;
                    case "$comment": break;
                    default: throw new FormatException("unknown field '" + kv.Key + "'");
                }
            }
            if (c.Id.Length == 0) throw new FormatException("missing 'id'");
            var dir = Path.GetFileName(Path.GetDirectoryName(f.Path));
            if (dir != c.Id) throw new FormatException("id '" + c.Id + "' must match folder name '" + dir + "'");
            return c;
        }

        /// <summary>"build_cost.wood" → "BuildCostWood".</summary>
        internal static string PascalCase(string key)
        {
            var sb = new StringBuilder();
            bool upper = true;
            foreach (char ch in key)
            {
                if (ch == '_' || ch == '.' || ch == '-') { upper = true; continue; }
                if (!char.IsLetterOrDigit(ch)) throw new FormatException("invalid character in key '" + key + "'");
                sb.Append(upper ? char.ToUpperInvariant(ch) : ch);
                upper = false;
            }
            return sb.ToString();
        }

        private static string Literal(string s) =>
            "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
