using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Rebuild.Analyzers
{
    /// <summary>
    /// Compiles data/goods.json (passed as AdditionalFiles) into C# tables (docs/06-economy.md §2). Good order in
    /// the file is the good index used in saves. Also emits <c>GoodIds</c> constants.
    /// </summary>
    [Generator(LanguageNames.CSharp)]
    public sealed class GoodDataGenerator : IIncrementalGenerator
    {
        private static readonly DiagnosticDescriptor BadData = new DiagnosticDescriptor(
            "RB0102", "Invalid good data", "{0}: {1}", "Data", DiagnosticSeverity.Error, isEnabledByDefault: true);

        /// <summary>Upper bound of a start stock (keeps stock arithmetic far from overflow).</summary>
        private const long MaxStart = 10000;

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var files = context.AdditionalTextsProvider
                .Where(f => Path.GetFileName(f.Path) == "goods.json")
                .Select((f, ct) => new FileData(f.Path, f.GetText(ct)?.ToString() ?? ""))
                .Collect();
            context.RegisterSourceOutput(files, Emit);
        }

        private sealed class FileData
        {
            public FileData(string path, string text) { Path = path; Text = text.Replace("\r", ""); }
            public string Path { get; }
            public string Text { get; }
        }

        private sealed class Good
        {
            public string Id = "";
            public string Name = "";
            public long Start;
        }

        private static void Emit(SourceProductionContext ctx, ImmutableArray<FileData> files)
        {
            if (files.Length == 0) return; // projects without good data (tools, tests)
            if (files.Length != 1)
            {
                ctx.ReportDiagnostic(Diagnostic.Create(BadData, Location.None, "goods.json",
                    "expected exactly one goods.json, found " + files.Length.ToString(CultureInfo.InvariantCulture)));
                return;
            }
            var file = files[0];
            List<Good> goods;
            try { goods = ReadGoods(file.Text); }
            catch (Exception e) when (CultureDataGenerator.IsDataError(e))
            {
                ctx.ReportDiagnostic(Diagnostic.Create(BadData, Location.None, file.Path, e.Message));
                return;
            }

            // FNV-1a 64 over the LF-normalized file, so all OS agree (same scheme as the other data hashes).
            ulong hash = 14695981039346656037UL;
            foreach (byte b in Encoding.UTF8.GetBytes(file.Text))
            {
                hash ^= b;
                hash *= 1099511628211UL;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> by Rebuild.Analyzers.GoodDataGenerator from data/goods.json </auto-generated>");
            sb.AppendLine("namespace Rebuild.Sim.Goods;");
            sb.AppendLine();
            sb.AppendLine("public static partial class GoodCatalog");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>Hash of data/goods.json; part of GameVersion.</summary>");
            sb.AppendLine("    public const ulong DataHash = 0x" + hash.ToString("X16", CultureInfo.InvariantCulture) + "UL;");
            sb.AppendLine();
            sb.AppendLine("    private static GoodDefinition[] CreateAll() => new GoodDefinition[]");
            sb.AppendLine("    {");
            for (int i = 0; i < goods.Count; i++)
            {
                var g = goods[i];
                sb.Append("        new GoodDefinition(").Append(i).Append(", ")
                  .Append(Literal(g.Id)).Append(", ").Append(Literal(g.Name)).Append(", ")
                  .Append(g.Start.ToString(CultureInfo.InvariantCulture)).AppendLine("),");
            }
            sb.AppendLine("    };");
            sb.AppendLine("}");
            sb.AppendLine();
            sb.AppendLine("/// <summary>Index of every good in data/goods.json.</summary>");
            sb.AppendLine("public static class GoodIds");
            sb.AppendLine("{");
            for (int i = 0; i < goods.Count; i++)
                sb.Append("    public const int ").Append(CultureDataGenerator.PascalCase(goods[i].Id))
                  .Append(" = ").Append(i).AppendLine(";");
            sb.AppendLine("}");
            ctx.AddSource("GoodCatalog.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static List<Good> ReadGoods(string text)
        {
            var root = (List<KeyValuePair<string, object?>>)MiniJson.Parse(text)!;
            var list = new List<Good>();
            foreach (var kv in root)
            {
                switch (kv.Key)
                {
                    case "goods":
                        foreach (var item in (List<object?>)kv.Value!)
                            list.Add(ReadGood((List<KeyValuePair<string, object?>>)item!));
                        break;
                    case "$comment": break;
                    default: throw new FormatException("unknown field '" + kv.Key + "'");
                }
            }
            if (list.Count == 0) throw new FormatException("no goods");
            if (list.Count > byte.MaxValue) throw new FormatException("too many goods");
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var g in list)
                if (!seen.Add(CultureDataGenerator.PascalCase(g.Id))) throw new FormatException("duplicate id '" + g.Id + "'");
            return list;
        }

        private static Good ReadGood(List<KeyValuePair<string, object?>> obj)
        {
            var g = new Good();
            foreach (var kv in obj)
            {
                switch (kv.Key)
                {
                    case "id": g.Id = (string)kv.Value!; break;
                    case "name": g.Name = (string)kv.Value!; break;
                    case "start":
                        g.Start = (long)kv.Value!;
                        if (g.Start < 0 || g.Start > MaxStart) throw new FormatException("'start' must be 0..10000");
                        break;
                    default: throw new FormatException("unknown field '" + kv.Key + "'");
                }
            }
            if (g.Id.Length == 0) throw new FormatException("good without 'id'");
            foreach (char ch in g.Id)
                if (!(ch >= 'a' && ch <= 'z') && !(ch >= '0' && ch <= '9') && ch != '_')
                    throw new FormatException("id '" + g.Id + "' must be lower snake case");
            if (g.Name.Length == 0) g.Name = g.Id;
            return g;
        }

        private static string Literal(string s) =>
            "\"" + s.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
    }
}
